config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
    }
  devise_for :admins, skip: :sessions
  devise_scope :admin do
    get "/admin/sign_in", to: "devise/sessions#new", as: :new_admin_session
    post "/admin/sign_in", to: "devise/sessions#create", as: :admin_session
    delete "/admin/sion_out", to: "devise/sessions#destroy", as: :destroy_admin_session
  end
  namespace :admin do
    get "/", to: 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  get '/' => 'homes#top', as: :homes
  get '/about' => 'homes#about', as: :about
  get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: :unsubscribe
  patch '/customers/:id/withdraw' => 'customers#withdraw', as: :withdraw
  resources :customers, only: [:show, :edit, :update]
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  resources :items, only: [:index, :show]
  resources :cart_items, only: [:index, :update, :destroy, :create] do
   delete '/enpty' => 'cart_items#enpty', as: :enpty
 end
 resources :orders, only: [:new, :create, :index, :show] do
   post '/confirm' => 'orders#confirm', as: :confirm
   get '/thanks' => 'orders#thanks', as: :thanks
 end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :orders, dependent: :destroy
 has_many :addresses, dependent: :destroy
 has_many :cart_items, dependent: :destroy

 validates :last_name, presence: true
 validates :first_name, presence: true
 validates :last_name_kana, presence: true
 validates :first_name_kana, presence: true
 validates :postal_code, presence: true
 validates :address, presence: true
 validates :telephone_number, presence: true
 validates :email, presence: true


  def full_name
    self.last_name + self.first_name
  end

  def full_name_kana
    self.last_name_kana + self.first_name_kana
  end

  enum is_active: {"有効": true, "退会": false}
  validates :is_active, inclusion: {in: ["有効", "退会"]}

  def active_for_authentication? #退会済み顧客が同じアカウントでログインできないようにする
    super && (is_active == "有効")
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
       redirect_to admin_customer_path(@customer.id)
    else
      render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:customer_id, :last_name, :first_name, :last_name_kana, :first_name_kana, :postale_code, :address, :telephone_number, :email, :is_active)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:attribut, :last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number])
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

    def reject_customer #退会後の同じ登録を阻止
      @customer = Customer.find_by(email: params[:customer][:email])
       if @customer
        if @customer.vaild_password?(params[:customer][:password]) && (@customer.is_active == "有効")
         flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
         redirect_to new_customer_registration_path
        else
         flash[:notice] = "項目を入力してください"
        end
       end
    end

end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer! #URLの直打ち禁止

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to customer_path(@customer.id)
  end

  def unsubscribe
    @customer = Customer.find(params[:id])
  end

  def withdraw
    @customer = Customer.find(params[:id])
    @customer.update(is_active: "退会") #false=退会に変更する
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用お待ちしております。"
    redirect_to homes_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name,:last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<div class="container mt-3">
 <div class="row">
   <div class="col mx-auto">
    <h4 class="page-title">プロフィール編集</h4>
    <%= form_with model: @customer, local: true do |f| %>
      <table>
        <tbody>
          <tr>
            <th>名前</th>
            <td>(姓)</td>
            <td><%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", class:'form-control' %></td>
            <td>(名)</td>
            <td><%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", class:'form-control' %></td>
          </tr>
          <tr>
            <th>フリガナ</th>
            <td>(セイ)</td>
            <td><%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana", class:'form-control' %></td>
            <td>(メイ)</td>
            <td><%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana", class:'form-control' %></td>
          </tr>
          <tr>
           <th>住所</th>
            <td></td>
            <td colspan="4"><%= f.text_field :address, autofocus: true, autocomplete: "address", class:'form-control' %></td>
          </tr>
          <tr>
           <th>郵便番号</th>
           <td></td>
           <td><%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", class:'form-control' %></td>
          </tr>
          <tr>
           <th>電話番号</th>
           <td></td>
           <td><%= f.text_field :telephone_number, autofocus: true, autocomplete: "telephone_number", class:'form-control' %></td>
          </tr>
          <tr>
           <th>メールアドレス</th>
           <td></td>
           <td><%= f.email_field :email, autofocus: true, autocomplete: "email", class:'form-control' %></td>
          </tr>
          <tr>
           <th></th>
           <td></td>
           <td><%= f.submit "変更を保存", class:'btn btn-success' %></td>
           <td><%= link_to '退会する',  unsubscribe_path(@customer.id), class:'btn btn-danger' %></td>
          </tr>
        </tbody>
      </table>
     <% end %>
    </div>
  </div>
</div>

app/views/customers/show.html.erb
<div class="container mt-3">
 <div class="row">
   <div class="col mx-auto">
    <h4 class="page-title">マイページ</h4>
     <h5><strong>登録情報</strong></h5>
     <%= link_to '編集する', edit_customer_path(@customer.id), class:'btn btn-success' %>
     <table class="table table-bordered">
        <tbody>
          <tr>
            <th>氏名</th>
            <td><%= @customer.full_name %></td>
          </tr>
            <th>カナ</th>
            <td><%= @customer.full_name_kana %></td>
          </tr>
            <th>郵便番号</th>
            <td><%= @customer.postal_code %></td>
          </tr>
            <th>住所</th>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
           <th>電話番号</th>
           <td><%= @customer.telephone_number %></td>
          </tr>
          <tr>
           <th>メールアドレス</th>
           <td><%= @customer.email %></td>
          </tr>
     </table>
     <div>
     <h5><strong>配送先</strong></h5>
     <%= link_to '一覧を見る', addresses_path, class:'btn btn-info' %>
     </div>
     <h5><strong>注文履歴</strong></h5>
     <%= link_to '一覧を見る', orders_path, class:'btn btn-primary' %>
     </div>
    </div>
  </div>
 </div>

app/views/customers/unsubscribe.html.erb
<div class="container mt-5">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-8 px-5 px-sm-0 mx-auto text-center">
   <h1><strong>本当に退会しますか？</strong></h1>
    <h4>退会すると、会員登録情報や</br>
    これまでの購入履歴が閲覧できなくなります。</br>
    退会する場合は、「退会する」をクリックしてください。</h4>

   <div>
    <%= link_to '退会しない', customer_path(@customer.id), class:'btn btn-info' %>
    <%= link_to '退会する', withdraw_path(@customer), method: :patch, "data-confirm" => "本当に退会しますか？", class:'btn btn-danger' %>
   </div>
  </div>
 </div>
</div>