config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
    }
  devise_for :admins, skip: :sessions
  devise_scope :admin do
    get "/admin/sign_in", to: "devise/sessions#new", as: :new_admin_session
    post "/admin/sign_in", to: "devise/sessions#create", as: :admin_session
    delete "/admin/sion_out", to: "devise/sessions#destroy", as: :destroy_admin_session
  end
  namespace :admin do
    get "/", to: 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  get '/' => 'homes#top', as: :homes
  get '/about' => 'homes#about', as: :about
  get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: :unsubscribe
  patch '/customers/:id/withdraw' => 'customers#withdraw', as: :withdraw
  resources :customers, only: [:show, :edit, :update]
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  resources :items, only: [:index, :show]
  resources :cart_items, only: [:index, :update, :destroy, :create] do
   delete '/enpty' => 'cart_items#enpty', as: :enpty
 end
 resources :orders, only: [:new, :create, :index, :show] do
   post '/confirm' => 'orders#confirm', as: :confirm
   get '/thanks' => 'orders#thanks', as: :thanks
 end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

belongs_to :customer
belongs_to :item

def subtotal
  item.with_tax_price * amount.to_i
end

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_customer!

  def index
    if customer_signed_in?
     @cart_items = current_customer.cart_items
    else
     redirect_to new_customer_session_path
    end
  end

  def update#数量の変更
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(amount: params[:amount].to_i)
    redirect_to cart_items_path
  end

  def destroy#1つの商品を削除
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path
  end

  def enpty#カート内の商品を全て削除
    current_customer.cart_items.destroy_all
    redirect_to cart_items_path
  end

  def create
    @item = Item.find(cart_item_params[:item_id])
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id
    if cart_item = current_customer.cart_items.find_by(item_id: params[:cart_item][:item_id])
       cart_item.amount += params[:cart_item][:amount].to_i
       cart_item.save
       redirect_to cart_items_path
    else
       @cart_item.save
       redirect_to cart_items_path
    end
  end

  private
  def cart_item_params
    params.require(:cart_item).permit(:item_id, :amount)
  end

end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<div class="container mt-3">
  <div class="row mx-auto">
    <div class="col pull-left">
     <h4 class="page-title">ショッピングカート</h4>
    </div>
    <div class="col text-right">
      <%= link_to 'カートを空にする', cart_item_enpty_path(current_customer.cart_items), method: :delete, class:'btn btn-danger' %>
    </div>
  </div>
  <div class="row table">
    <table class="table table-hove mt-3">
      <thead class="table-warning bg-opacity-10">
       <tr>
         <th>商品名</th>
         <th>単価(税込)</th>
         <th>数量</th>
         <th>小計</th>
         <th></th>
       </tr>
      </thead>
      <tboby>
        <% @total_price = 0 %>
        <% @cart_items.each do |cart_item| %>
         <tr>
          <td>
           <%= attachment_image_tag cart_item.item, :image, :fill, 60, 60, format:'jpg', class:'border border-light' %><%= cart_item.item.name %>
          </td>
          <td><%= cart_item.item.with_tax_price.to_s(:delimited) %></td>
          <td>
            <%= form_with model: @cart_item, url: cart_item_path(cart_item.id), method: :put, local:true do |f| %>
            <%= f.select :amount, options_for_select(*[1..10], {selected: cart_item.amount.to_i}) %>
            <%= f.submit '変更', class:'btn btn-success'%>
            <% end %>
          </td>
          <td><%=  cart_item.subtotal.to_s(:delimited) %></td>
          <td><%= link_to '削除する', cart_item_path(cart_item), method: :delete, class:'btn btn-danger' %>
          <% @total_price += cart_item.subtotal %>
         </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="row total">
    <div class="col text-left">
      <%= link_to '買い物を続ける', homes_path, class:'btn btn-info' %>
    </div>
    <div class="col text-right">
     <table class="table table-bordered">
      <tbody>
       <tr>
        <td class="col-3 text-center">合計金額</td>
        <td class="col-3 text-center">¥ <%= @total_price.to_s(:delimited) %></td>
       </tr>
      </tbody>
     </table>
    </div>
  </div>
  <div class="row next-btn">
   <div class="col text-right">
     <% if @cart_items.blank? %>
       <% else %>
       <%= link_to '注文情報入力に進む', new_order_path, class:'btn btn-success' %>
     <% end %>
   </div>
  </div>
</div>