config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
    }
  devise_for :admins, skip: :sessions
  devise_scope :admin do
    get "/admin/sign_in", to: "devise/sessions#new", as: :new_admin_session
    post "/admin/sign_in", to: "devise/sessions#create", as: :admin_session
    delete "/admin/sion_out", to: "devise/sessions#destroy", as: :destroy_admin_session
  end
  namespace :admin do
    get "/", to: 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
  get '/' => 'homes#top', as: :homes
  get '/about' => 'homes#about', as: :about
  get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: :unsubscribe
  patch '/customers/:id/withdraw' => 'customers#withdraw', as: :withdraw
  resources :customers, only: [:show, :edit, :update]
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  resources :items, only: [:index, :show]
  resources :cart_items, only: [:index, :update, :destroy, :create] do
   delete '/enpty' => 'cart_items#enpty', as: :enpty
 end
 resources :orders, only: [:new, :create, :index, :show] do
   post '/confirm' => 'orders#confirm', as: :confirm
   get '/thanks' => 'orders#thanks', as: :thanks
 end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_adminheader.html.erb
<header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/admin"><%= image_tag 'logo._image1.PNG', :size => '180x60' %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
             <li class="nav-item">
              <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark' %>
             </li>
              <li class="nav-item">
              <%= link_to '会員一覧', admin_customers_path, class: 'nav-link text-dark' %>
             </li>
            <li class="nav-item">
              <%= link_to '注文履歴一覧', admin_path, class: 'nav-link text-dark' %>
             </li>
             <li class="nav-item">
              <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-dark' %>
             </li>
             <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
             </li>
            </ul>
          </div>
        </div>
      </nav>
</header>

app/views/layouts/_header.html.erb
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag 'logo._image1.PNG', :size => '180x60' %></a>
          <% if customer_signed_in? %>
          <h6>ようこそ、<%= current_customer.last_name %>さん！</h6>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
             <li class="nav-item">
              <%= link_to "マイページ", customer_path(current_customer.id), class: 'nav-link text-dark' %>
             </li>
             <li class="nav-item">
              <%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %>
             </li>
             <li class="nav-item">
              <%= link_to "カート", cart_items_path, class: 'nav-link text-dark' %>
             </li>
             <li class="nav-item">
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
             </li>
             <% else %>
             <li class="nav-item">
              <%= link_to "ABOUT", about_path, class: 'nav-link text-dark' %>
             </li>
             <li class="nav-item">
              <%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %>
             </li>
             <li class="nav-item">
              <%= link_to '新規登録',new_customer_registration_path, class: 'nav-link text-dark' %>
             </li>
             <li class="nav-item">
              <%= link_to "ログイン", customer_session_path, class: 'nav-link text-dark' %>
             </li>
             <% end %>

            </ul>
          </div>
        </div>
      </nav>

app/views/layouts/adminheader.html.erb
<header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/admin"><%= image_tag 'logo._image1.PNG', :size => '180x60' %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
             <li class="nav-item">
              <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark' %>
             </li>
              <li class="nav-item">
              <%= link_to '会員一覧', admin_customers_path, class: 'nav-link text-dark' %>
             </li>
            <li class="nav-item">
              <%= link_to '注文履歴一覧', admin_path, class: 'nav-link text-dark' %>
             </li>
             <li class="nav-item">
              <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-dark' %>
             </li>
             <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
             </li>
            </ul>
          </div>
        </div>
      </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body class="d-flex flex-column vh-100">
   <header class="he">

        <% if admin_signed_in? %>
            <%= render 'layouts/adminheader' %>
        <% else %>
            <%= render 'layouts/header' %>
        <% end %>

   </header>

    <main class="mb-auto">
    <%= yield %>
    </main>

    <footer class="bg-light pt-5 pb-4">
      <div class="container text-center">
        <div class="row no-gutters">
          <div class="col">
            <p>Nagano Cake</p>
          </div>
        </div>
      </div>
    </footer>
  </body>

</html>

app/views/layouts/header.html.erb
   <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/admin"><%= image_tag 'logo._image1.PNG', :size => '180x60' %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
             <li class="nav-item">
              <%= link_to "マイページ", , class: 'nav-link text-dark' %>
             </li>
              <li class="nav-item">
              <%= link_to '商品一覧', , class: 'nav-link text-dark' %>
             </li>
            <li class="nav-item">
              <%= link_to 'カート', h, class: 'nav-link text-dark' %>
             </li>
             <li class="nav-item">
              <%= link_to "ログアウト", , method: :delete, class: 'nav-link text-dark' %>
             </li>
             <% else %>
             <li class="nav-item">
              <%= link_to "ABOUT", , class: 'nav-link text-dark' %>
             </li>
              <li class="nav-item">
              <%= link_to '商品一覧', , class: 'nav-link text-dark' %>
             </li>
            <li class="nav-item">
              <%= link_to '新規登録', , class: 'nav-link text-dark' %>
             </li>
             <li class="nav-item">
              <%= link_to "ログイン", , class: 'nav-link text-dark' %>
             </li>
             <% end %>

            </ul>
          </div>
        </div>
      </nav>
    </header>